### PR TITLE
Added uma0 for Vita Memory Card

### PR DESCRIPTION
**Pull request by devnoname120**
Edit: [a fork](https://github.com/CelesteBlue-dev/PSVita-StorageMgr) implemented this feature

### CODE REVIEW

**Comment by CelesteBlue-dev** [comment]
Do you have tried this version on PSTV ?
There is a problem with mounting uma0 on PSTV.

**Comment by xyzz** [comment]
I think it's not a good idea to hardcode any more logic. It would be better to have a configuration file, where users can specify the type of redirect they want (this file can just contain a number), for example:

* 0 (default): microsd redirected to ux0, mc is disabled
* 1: microsd redirected to ux0, mc to uma0
* 2: microsd to uma0, mc stays ux0

**Comment by aagallag** [comment]
I've got the configuration file working on [my fork](https://github.com/aagallag/gamecard-microsd) for scenario 0 and 1.  I will probably hold off on opening a new PR until I figure out how to implement scenario 2.

**Comment by mathieulh** [comment]
Not to sound picky, but shouldn't we mount the SD card as sd0:/ (in addition to other mount-points) since that's pretty much what it is originally supposed to be, DEM-3000 used to support sd0:/ in place of gro0:/ and grw:/, the references still exist in 3.60 but the mount point isn't used because there's no SD card reader anymore (although arguably the game card reader is one).

**Comment by Rameron** [comment]
On 3.65 sd-card mount as ux0, but vita card don't mount as uma0. It's absolutely not mount anyway. How can I fix this?

**Comment by srmoska** [comment]
Just updated to 3.65, vita card not mounting to uma0 like when on 3.60 is this normal, is there a way to fix this? Thanks in advance

**Comment by xyzz** [comment]
https://github.com/xyzz/gamecard-microsd/issues/24#issuecomment-372734226

**Pull request closed without merging**
